# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Arf2.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nArf2.proto\")\n\tWishChild\x12\x0c\n\x04info\x18\x01 \x01(\x04\x12\x0e\n\x06\x61nodes\x18\x02 \x03(\r\"D\n\tWishGroup\x12\x0c\n\x04info\x18\x01 \x01(\r\x12\r\n\x05nodes\x18\x02 \x03(\x04\x12\x1a\n\x06\x63hilds\x18\x03 \x03(\x0b\x32\n.WishChild\"\'\n\tArf2Index\x12\x0c\n\x04widx\x18\x01 \x03(\r\x12\x0c\n\x04hidx\x18\x02 \x03(\r\"\xe9\x01\n\x04\x41rf2\x12\x0f\n\x07init_ms\x18\x01 \x01(\r\x12\x0e\n\x06\x65nd_ms\x18\x02 \x01(\r\x12\x13\n\x0btotal_hints\x18\x03 \x01(\r\x12\x14\n\x0cwgo_required\x18\x04 \x01(\r\x12\x14\n\x0chgo_required\x18\x05 \x01(\r\x12\x18\n\x04wish\x18\x06 \x03(\x0b\x32\n.WishGroup\x12\x0c\n\x04hint\x18\x07 \x03(\x04\x12\x14\n\x0cspecial_hint\x18\x08 \x01(\r\x12\x12\n\ndts_layer1\x18\t \x03(\x04\x12\x12\n\ndts_layer2\x18\n \x03(\x04\x12\x19\n\x05index\x18\x0b \x03(\x0b\x32\n.Arf2IndexB\x05H\x03\xf8\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Arf2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003\370\001\000'
  _globals['_WISHCHILD']._serialized_start=14
  _globals['_WISHCHILD']._serialized_end=55
  _globals['_WISHGROUP']._serialized_start=57
  _globals['_WISHGROUP']._serialized_end=125
  _globals['_ARF2INDEX']._serialized_start=127
  _globals['_ARF2INDEX']._serialized_end=166
  _globals['_ARF2']._serialized_start=169
  _globals['_ARF2']._serialized_end=402
# @@protoc_insertion_point(module_scope)
